


### Text mining



### Load Libraries and data
```{r}

library(tidyverse)
library(tidytext)
#library(qdap)

#data <- read.csv("text.data.csv")
data <- read.csv("long.data.csv")
```


### Simple plots
```{r}
level.n <- data %>% filter(level!="?") %>% group_by(Subgenus, level) %>% count(level)

ggplot(level.n, aes(Subgenus,fill=level, y=n)) +  geom_bar(stat="identity", color="black")+scale_fill_manual(values=c("#FF9912","#BDB76B","#65909A")) +theme_bw() +coord_flip() +theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + ylab("count")+ scale_y_continuous(expand = c(0, 0), limits = c(0, 160)) 

habitat.n <- data %>% filter(Habitat!="?") %>% group_by(Subgenus, Habitat) %>% count(Habitat)

ggplot(habitat.n, aes(Subgenus,fill=Habitat, y=n)) +  geom_bar(stat="identity", color="black") +scale_fill_manual(values=c("#BDB76B","#65909A","#FF9912","#A68064","#48426C","#B7C3D0")) +theme_bw() +coord_flip() +theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + ylab("count")+ 
scale_y_continuous(expand = c(0, 0), limits = c(0, 160)) 
```
### Plots with revised patch data
```{r}
data2 <- read.csv("revised.data.csv")

## compare level

data.lvl <- data2 %>%  mutate(ground.location = strsplit(as.character(ground.location), " and ")) %>% unnest(ground.location)
data.lvl <- cbind(data.lvl[,c("uniqueID","subgenus","ground.location")])


level.n <- data.lvl %>% filter(ground.location!="N/A") %>% group_by(subgenus, ground.location) %>% count(ground.location)

lvl1 <- ggplot(level.n, aes(subgenus,fill=ground.location, y=n)) +  geom_bar(stat="identity", color="black")+scale_fill_manual(values=c("#FF9912","#BDB76B","#65909A")) +theme_bw() +coord_flip() +theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + ylab("count")+ scale_y_continuous(expand = c(0, 0), limits = c(0, 30))  +theme(legend.title=element_blank())+ theme(axis.text=element_text(colour="black", size=14),text=element_text(colour="black", size=14)) + xlab("")

data.plvl <- data2 %>%  mutate(level.pref = strsplit(as.character(level.pref), " and ")) %>% unnest(level.pref)
data.plvl <- cbind(data.plvl[,c("uniqueID","subgenus","level.pref")])
data.plvl <- data.plvl[!duplicated(data.plvl ), ]

plevel.n <- data.plvl %>% filter(level.pref!="?") %>% group_by(subgenus, level.pref) %>% count(level.pref)

lvl2 <- ggplot(plevel.n, aes(subgenus,fill=level.pref, y=n)) +  geom_bar(stat="identity", color="black")+scale_fill_manual(values=c("#FF9912","#BDB76B","#65909A")) +theme_bw() +coord_flip() +theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + ylab("count")+ scale_y_continuous(expand = c(0, 0), limits = c(0, 30)) 

require(gridExtra)

grid.arrange(lvl1,lvl2, ncol=2)



data.lnd <- data2 %>%  mutate(Landscape.graph = strsplit(as.character(Landscape.graph), " and ")) %>% unnest(Landscape.graph)
data.lnd <- cbind(data.lnd[,c("uniqueID","subgenus","Landscape.graph","nest.total")])
data.lnd2 <- data.lnd %>%  mutate(Landscape.graph = strsplit(as.character(Landscape.graph), ", ")) %>% unnest(Landscape.graph)
unique(data.lnd2$Landscape.graph)

## Combined Human disturbed, wetland, and shrubland into an "other" category
data.lnd2$Landscape.graph <- gsub("wetland", "other", data.lnd2$Landscape.graph) ## replaced wetland with other
data.lnd2$Landscape.graph <- gsub("shrubland", "other", data.lnd2$Landscape.graph) ## replaced shrubland with other
data.lnd2$Landscape.graph <- gsub("human disturbed", "other", data.lnd2$Landscape.graph) ## replaced human disturbed with other
data.lnd2$Landscape.graph <- gsub("dune", "other", data.lnd2$Landscape.graph) ## replaced dune with other

avg.lnd2 <- data.lnd2 %>%  group_by(subgenus, Landscape.graph) %>% summarize(nest.total=sum(nest.total))

ggplot(avg.lnd2 , aes(x=subgenus,y=nest.total, fill=Landscape.graph)) +  geom_bar(stat="identity", color="black", position="fill") +scale_fill_manual(values=c("#325C74","#388E8E","#03A89E","#AEEEEE","#D4ED91","#BCED91","#629632","#46523C")) +theme_bw() +coord_flip() +theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + ylab("proportion of nests")


## Old palette
## +scale_fill_manual(values=c("#BDB76B","#65909A","#FF9912","#A68064","#48426C","#B7C3D0","Grey50","Grey80"))
write.csv(data.lnd2, "landscape.bombus.nestabd.csv")
```

### Habitat by plot
```{r}
data2 <- read.csv("revised.data2.wnest.csv")

data.lnd <- data2 %>%  mutate(Landscape.graph = strsplit(as.character(Landscape.graph), " and ")) %>% unnest(Landscape.graph)
data.lnd <- cbind(data.lnd[,c("uniqueID","ground.location.of.nest","Landscape.graph","nest.total")])
data.lnd2 <- data.lnd %>%  mutate(Landscape.graph = strsplit(as.character(Landscape.graph), ", ")) %>% unnest(Landscape.graph)
unique(data.lnd2$Landscape.graph)

## Combined Human disturbed, wetland, and shrubland into an "other" category
data.lnd2$Landscape.graph <- gsub("wetland", "other", data.lnd2$Landscape.graph) ## replaced wetland with other
data.lnd2$Landscape.graph <- gsub("shrubland", "other", data.lnd2$Landscape.graph) ## replaced shrubland with other
data.lnd2$Landscape.graph <- gsub("human disturbed", "other", data.lnd2$Landscape.graph) ## replaced human disturbed with other
data.lnd2$Landscape.graph <- gsub("dune", "other", data.lnd2$Landscape.graph) ## replaced dune with other

avg.lnd2 <- data.lnd2 %>%  group_by(ground.location.of.nest, Landscape.graph) %>% summarize(nest.total=sum(nest.total))

ggplot(avg.lnd2 , aes(x=Landscape.graph,y=nest.total, fill=ground.location.of.nest)) +  geom_bar(stat="identity", color="black", position="fill") +scale_fill_manual(values=c("#629632","#D4ED91","#325C74")) +theme_bw() +coord_flip() +theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + ylab("proportion of nests") +xlab("landscape type")


write.csv(data.lnd2, "nestlvl.bombus.landscape.csv")

data2 <- read.csv("revised.data2.wnest.csv")


avg.lnd2 <- data2 %>%  group_by(ground.location.of.nest, subgenus) %>% summarize(nest.total=sum(nest.total))

ggplot(avg.lnd2 , aes(x=subgenus,y=nest.total, fill=ground.location.of.nest)) +  geom_bar(stat="identity", color="black", position="fill") +scale_fill_manual(values=c("#629632","#D4ED91","#325C74")) +theme_bw() +coord_flip() +theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + ylab("proportion of nests") +xlab("subgenus")


write.csv(avg.lnd2, "nestlvl.bombus.nestabd.csv")

```


### Regenerate Plots with Species porportions
```{r}

data2 <- read.csv("revised.data.csv")


data.lnd <- data2 %>%  mutate(Landscape.graph = strsplit(as.character(Landscape.graph), " and ")) %>% unnest(Landscape.graph)
data.lnd <- cbind(data.lnd[,c("uniqueID","subgenus","Landscape.graph","Species")])
data.lnd2 <- data.lnd %>%  mutate(Landscape.graph = strsplit(as.character(Landscape.graph), ", ")) %>% unnest(Landscape.graph)
unique(data.lnd2$Landscape.graph)

## Combined Human disturbed, wetland, and shrubland into an "other" category
data.lnd2$Landscape.graph <- gsub("wetland", "other", data.lnd2$Landscape.graph) ## replaced wetland with other
data.lnd2$Landscape.graph <- gsub("shrubland", "other", data.lnd2$Landscape.graph) ## replaced shrubland with other
data.lnd2$Landscape.graph <- gsub("human disturbed", "other", data.lnd2$Landscape.graph) ## replaced human disturbed with other
data.lnd2$Landscape.graph <- gsub("dune", "other", data.lnd2$Landscape.graph) ## replaced dune with other

avg.lnd2 <- data.lnd2 %>%  group_by(subgenus, Landscape.graph) %>% summarize(spp.n=length(Species))

ggplot(avg.lnd2 , aes(x=subgenus,y=spp.n, fill=Landscape.graph)) +  geom_bar(stat="identity", color="black", position="fill") +scale_fill_manual(values=c("#325C74","#388E8E","#11d8cc","#AEEEEE","#D4ED91","#BCED91","#629632","#46523C")) +theme_bw() +coord_flip() +theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + ylab(expression("proportion of "*italic("Bombus")*" species"))



data2 <- read.csv("revised.data2.wnest.csv")

data.lnd <- data2 %>%  mutate(Landscape.graph = strsplit(as.character(Landscape.graph), " and ")) %>% unnest(Landscape.graph)
data.lnd <- cbind(data.lnd[,c("uniqueID","ground.location.of.nest","Landscape.graph","Species")])
data.lnd2 <- data.lnd %>%  mutate(Landscape.graph = strsplit(as.character(Landscape.graph), ", ")) %>% unnest(Landscape.graph)
unique(data.lnd2$Landscape.graph)

## Combined Human disturbed, wetland, and shrubland into an "other" category
data.lnd2$Landscape.graph <- gsub("wetland", "other", data.lnd2$Landscape.graph) ## replaced wetland with other
data.lnd2$Landscape.graph <- gsub("shrubland", "other", data.lnd2$Landscape.graph) ## replaced shrubland with other
data.lnd2$Landscape.graph <- gsub("human disturbed", "other", data.lnd2$Landscape.graph) ## replaced human disturbed with other
data.lnd2$Landscape.graph <- gsub("dune", "other", data.lnd2$Landscape.graph) ## replaced dune with other

avg.lnd2 <- data.lnd2 %>%  group_by(ground.location.of.nest, Landscape.graph) %>% summarize(spp.n=length(Species))

ggplot(avg.lnd2 , aes(x=Landscape.graph,y=spp.n, fill=ground.location.of.nest)) +  geom_bar(stat="identity", color="black", position="fill") +scale_fill_manual(values=c("#629632","#D4ED91","#325C74")) +theme_bw() +coord_flip() +theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + ylab(expression("proportion of "*italic("Bombus")*" species")) +xlab("landscape type")




data2 <- read.csv("revised.data2.wnest.csv")


avg.lnd2 <- data2 %>%  group_by(ground.location.of.nest, subgenus) %>% summarize(spp.n=length(Species))

ggplot(avg.lnd2 , aes(x=subgenus,y=spp.n, fill=ground.location.of.nest)) +  geom_bar(stat="identity", color="black", position="fill") +scale_fill_manual(values=c("#629632","#D4ED91","#325C74")) +theme_bw() +coord_flip() +theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + ylab(expression("proportion of "*italic("Bombus")*" species")) +xlab("subgenus")
```





### Clean up text
```{r}

text_df <- data_frame(text=as.character(data$Habitat.summary))

word.count <- text_df %>% unnest_tokens(word,text) %>%  dplyr::count(word, sort=T) ## count words

## list stop words
stopwords <- c(stop_words$word, "studies", "areas", "found", "also", "nest","nests","surrounding","conducted","8","6","prefers","study","included","sites","50","1000m","prefer","including","habitat","reported","habitats","possibly")
stopwords <- c(stopwords,"11","200","500","9","10","17","objects","site","suggest","type","750","stated","4","surveyed","commonly","preferred","terms","types","chosen","comparing","determine","common","fairly","energy","intake","locations","looked","maximize","mid","net","preferentially","species","randomly","nesting","constructed","landscapes","entrance","thin","forage","conflicted","regularly","lapidarius","pascuorum","withered","ecosystem","existing","lucorum","considered","low","pre","dried", "nested","ground")

## identify stop words
stop1 <- text_df %>% unnest_tokens(word,text)
stop2 <- stop1[!stop1$word %in% stopwords,]
stop3 <- stop2 %>% dplyr::count(word, sort=T)

## Remove stop words and get into long format
df <- data.frame()

for(i in 1:nrow(text_df)){
temp <- text_df[i,1]%>%  unnest_tokens(word,text) 
temp[,"id"] <- paste(i)
df <- rbind(df, temp)
}

## remove simple words
simple.text <- df[!df$word %in% stopwords,]

simple.text <- data.frame(simple.text)
simple.text[,"value"] <- 1

## replace plurals
simple.text[simple.text$word=="tussocks","word"] <- "tussock"
simple.text[simple.text$word=="fences","word"] <- "fence"
simple.text[simple.text$word=="forests","word"] <- "forest"
simple.text[simple.text$word=="cavity","word"] <- "cavities"
simple.text[simple.text$word=="grasslands","word"] <- "grassland"
simple.text[simple.text$word=="mountains","word"] <- "mountain"
simple.text[simple.text$word=="interface","word"] <- "interspace"
simple.text[simple.text$word=="boundaries","word"] <- "boundary"

simple.text <- simple.text[!duplicated(simple.text),] ## remove duplicates


## create matrix of ID by words
matrix.words <- spread(simple.text, word, value, fill=0)
rownames(matrix.words) <- matrix.words$id
matrix.words[,1:6] <- NULL
matrix.words <- cor(t(matrix.words))

## remove perfect matches
matrix.words[matrix.words==1] <- 0

matrix.words <- data.frame(matrix.words)
matrix.words[is.na(matrix.words)] <- 0
```



### Determine correlations
```{r}

## merge with original dataframe
data["id"] <- row.names(data)
matrix.words["id"] <- row.names(matrix.words)
data.text <- merge(data, matrix.words, by="id")

## long-wise data
data.text <- gather(data.text, row.id, correlation, 16:174)

## determine baseline
mean(data.text$correlation)
sqrt(var(data.text$correlation)/length(data.text$correlation))*1.96

### compare variables

## IUCN status
status <- data.text %>% group_by(IUCN.status) %>% summarize(cor=mean(correlation))

## Tounge length
toungue <- data.text %>% group_by(toungue.length) %>% summarize(cor=mean(correlation))

## subgenus
subgenus <- data.text %>% group_by(Subgenus) %>% summarize(cor=mean(correlation))

## start month
smonth <- data.text %>% group_by(Start.month) %>% summarize(cor=mean(correlation))

## end month
emonth <- data.text %>% group_by(End.month) %>% summarize(cor=mean(correlation))

## geography
geo <- data.text %>% group_by(Continent) %>% summarize(cor=mean(correlation))

## detection
detect <- data.text %>% group_by(detection.method) %>% summarize(cor=mean(correlation))


## habitat
Habitat <- data.text %>% group_by(Habitat) %>% summarize(cor=mean(correlation))
```

## wordclouds
```{r}

library(wordcloud)
library(reshape2)
simple.data <- merge(data, simple.text, by="id")
cloud.data <- simple.data %>% filter(Start.month!="?") %>%  group_by(Start.month,word) %>% summarize(n=sum(value))
cloud.data %>% acast(word~Start.month, value.var="n", fill=0) %>% comparison.cloud(max.words=100)

simple.data <- merge(data, simple.text, by="id")
cloud.data <- simple.data %>% group_by(Subgenus,word) %>% summarize(n=sum(value))
cloud.data %>% acast(word~Subgenus, value.var="n", fill=0) %>% comparison.cloud(max.words=100, title.size=1, random.order=FALSE)

simple.data <- merge(data, simple.text, by="id")
cloud.data <- simple.data %>% group_by(IUCN.status,word) %>% summarize(n=sum(value))
cloud.data %>% acast(word~IUCN.status, value.var="n", fill=0) %>% comparison.cloud(max.words=100, title.size=1.5, random.order=FALSE)

simple.data <- merge(data, simple.text, by="id")
cloud.data <- simple.data %>% group_by(toungue.length,word) %>% summarize(n=sum(value))
cloud.data %>% acast(word~toungue.length, value.var="n", fill=0) %>% comparison.cloud(max.words=100)

simple.data <- merge(data, simple.text, by="id")
cloud.data <- simple.data %>% group_by(End.month,word) %>% summarize(n=sum(value))
cloud.data %>% acast(word~End.month, value.var="n", fill=0) %>% comparison.cloud(max.words=100)

simple.data <- merge(data, simple.text, by="id")
cloud.data <- simple.data %>% group_by(Continent,word) %>% summarize(n=sum(value))
cloud.data %>% acast(word~Continent, value.var="n", fill=0) %>% comparison.cloud(max.words=100,title.size=1.5, random.order=FALSE)


simple.data <- merge(data, simple.text, by="id")
cloud.data <- simple.data %>% group_by(Continent,word) %>% summarize(n=sum(value))
cloud.data %>% acast(word~Continent, value.var="n", fill=0) %>% comparison.cloud(max.words=100,title.size=1.5, random.order=FALSE)

simple.data <- merge(data, simple.text, by="id")
cloud.data <- simple.data %>% filter(Habitat!="?") %>%  group_by(Habitat,word) %>% summarize(n=sum(value))
cloud.data %>% acast(word~Habitat, value.var="n", fill=0) %>% comparison.cloud(max.words=110,title.size=1.5, random.order=FALSE)

simple.data <- merge(data, simple.text, by="id")
cloud.data <- simple.data %>% filter(level!="?") %>% group_by(level,word) %>% summarize(n=sum(value))
cloud.data %>% acast(word~level, value.var="n", fill=0) %>% comparison.cloud(max.words=110,title.size=1.5, random.order=FALSE)

```



### Final JOIC figures
```{r}
data3 <- read.csv("JOICdata_split2.csv")

str(data3)


data.lnd <- data3 %>%  mutate(Landscape.graph = strsplit(as.character(Landscape.graph), " and ")) %>% unnest(Landscape.graph)
data.lnd <- cbind(data.lnd[,c("uniqueID","subgenus","Landscape.graph","Species")])
data.lnd2 <- data.lnd %>%  mutate(Landscape.graph = strsplit(as.character(Landscape.graph), ", ")) %>% unnest(Landscape.graph)
unique(data.lnd2$Landscape.graph)

## Combined Human disturbed, wetland, and shrubland into an "other" category
data.lnd2$Landscape.graph <- gsub("wetland", "other", data.lnd2$Landscape.graph) ## replaced wetland with other
data.lnd2$Landscape.graph <- gsub("shrubland", "other", data.lnd2$Landscape.graph) ## replaced shrubland with other
data.lnd2$Landscape.graph <- gsub("human disturbed", "other", data.lnd2$Landscape.graph) ## replaced human disturbed with other
data.lnd2$Landscape.graph <- gsub("dune", "other", data.lnd2$Landscape.graph) ## replaced dune with other

avg.lnd2 <- data.lnd2 %>%  group_by(subgenus, Landscape.graph) %>% summarize(spp.n=length(Species))

## Remove spaces
avg.lnd2$Landscape.graph <- gsub(" ", "", avg.lnd2$Landscape.graph, fixed = TRUE)
avg.lnd2$Landscape.graph <- gsub("tropicalforest", "tropical forest", avg.lnd2$Landscape.graph, fixed = TRUE)
avg.lnd2$Landscape.graph <- gsub("forestedge", "forest edge", avg.lnd2$Landscape.graph, fixed = TRUE)


ggplot(avg.lnd2 , aes(x=subgenus,y=spp.n, fill=Landscape.graph)) +  geom_bar(stat="identity", color="black", position="fill") +scale_fill_manual(values=c("#325C74","#388E8E","#11d8cc","#AEEEEE","#D4ED91","#BCED91","#629632","#46523C")) +theme_bw() +coord_flip() +theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + ylab(expression("proportion of "*italic("Bombus")*" species"))


```
